# For developemnt use only.
version: "3.8"
services:
  tigergraph:
    image: tigergraph/tigergraph:3.9.1
    ports:
    # API (HTTP)
    - 127.0.0.1:9001:9000
    # Dashboard (HTTP)
    - 127.0.0.1:14240:14240
    # SSH (TCP)
    - 127.0.0.1:14022:22
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
