version: '3.8'
services:
  server:
    image: ghcr.io/nextdotid/relation_server:main
    environment:
      # Enable this if you meet anything wrong
      #RUST_BACKTRACE: full
      RELATION_SERVER_ENV: production
    volumes:
    - ./config:/app/config:ro
    depends_on:
    - tigergraph
    ports:
    - 127.0.0.1:8000:8000
  tigergraph:
    image: tigergraph/tigergraph:3.9.1
    ports:
    # API (HTTP)
    - 127.0.0.1:9001:9000
    # Dashboard (HTTP)
    - 127.0.0.1:14240:14240
    # SSH (TCP)
    - 127.0.0.1:14022:22
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
