[tdb]
host = "http://localhost:9001"
username = "tigergraph"
password = "tigergraph"
identity_graph_token = "01234567abcdefgh01234567abcdefgh"
social_graph_token = "01234567abcdefgh01234567abcdefgh"

[web]
listen = "127.0.0.1"
port = 3722

[upstream.proof_service]
url = "https://proof-service.next.id"
api_key = "x-api-key"

[upstream.aggregation_service]
url = "http://data-server-hostname/data_server"

[upstream.sybil_service]
url = "https://raw.githubusercontent.com/Uniswap/sybil-list/master/verified.json"

[upstream.keybase_service]
url = "https://keybase.io/_/api/1.0/user/lookup.json"
stable_url = "http://data-server-hostname/data_server/keybase"

[upstream.knn3_service]
url = "https://mw.graphql.knn3.xyz/"

[upstream.rss3_service]
url = "https://pregod.rss3.dev/v1/notes"

[upstream.the_graph]
ens = "https://gateway-arbitrum.network.thegraph.com/api/[your_api_key]/subgraphs/id/{your_subgraph_id}"

[upstream.ens_reverse]
url = "https://ens.fafrd.workers.dev/ens/"

[upstream.dotbit_service]
url = "https://indexer-v1.did.id"

[upstream.lens_api]
url = "https://api-v2.lens.dev/playground"

[upstream.unstoppable_api]
url = "https://api.unstoppabledomains.com"
token = "4cb4358d-ce8b-4bf5-fill-yourstokenid"

[upstream.datamgr_api]
url = "https://cryptodata.store"

[upstream.warpcast_api]
url = "https://api.warpcast.com"
token = "MK-ABC123..."

[upstream.spaceid_api]
url = "https://api.prd.space.id"

[upstream.crossbell_api]
url = "https://indexer.crossbell.io/v1/graphql"

[upstream.solana_rpc]
rpc_url = "https://api.mainnet-beta.solana.com"

[upstream.genome_api]
rpc_url = "http://data-server-hostname/data_server/genome"
