[db]
host = "http://127.0.0.1:8529"
username = "root"
password = "ieNgoo5roong9Chu"
db = "relation_server_development"
schema_path = "./src/config/db/schema.yaml"

[web]
listen = "127.0.0.1"
port = 3722

[upstream.proof_service]
url = "https://proof-service.next.id"

[upstream.aggregation_service]
url = "https://7x16bogxfb.execute-api.us-east-1.amazonaws.com/v1/identity/search"

[upstream.sybil_service]
url = "https://raw.githubusercontent.com/Uniswap/sybil-list/master/verified.json"

[upstream.keybase_service]
url = "https://keybase.io/_/api/1.0/user/lookup.json"

[upstream.knn3_service]
url = "https://mw.graphql.knn3.xyz/"

[upstream.rss3_service]
url = "https://pregod.rss3.dev/v1/notes"

[upstream.the_graph]
ens = "https://api.thegraph.com/subgraphs/name/ensdomains/ens"

[upstream.ens_reverse]
url = "https://ens.fafrd.workers.dev/ens/"

[upstream.dotbit_service]
url = "https://indexer-basic.did.id"

[upstream.lens_api]
url = "https://api.thegraph.com/subgraphs/name/anudit/lens-protocol"