# The migration files contain two sections:
# - up: The commands to execute on migration
# - down: The commands to execute on rollback (optional)
# check https://docs.rs/aragog_cli for complete documentation and examples
---
up:
  - create_collection:
      name: Contracts
  - delete_collection:
      name: NFTs
down:
  - delete_collection:
      name: Contracts
  - create_collection:
      name: NFTs
