use crate::{
    error::Error,
    graph::vertex::IdentityRecord,
    tigergraph::{
        edge::{Edge, EdgeRecord, FromWithParams, Wrapper},
        vertex::{Identity, Vertex},
        Attribute, EdgeWrapper, OpCode, Transfer,
    },
    upstream::{DataFetcher, DataSource},
    util::{
        naive_datetime_from_string, naive_datetime_to_string, naive_now,
        option_naive_datetime_from_string, option_naive_datetime_to_string, parse_body,
    },
};

use async_graphql::{Enum, ObjectType, SimpleObject};
use chrono::{Duration, NaiveDateTime};
use hyper::{client::HttpConnector, Body, Client, Request};
use serde::{Deserialize, Serialize};
use serde_json::{json, to_value};
use serde_repr::{Deserialize_repr, Serialize_repr};
use std::collections::HashMap;
use strum_macros::{Display, EnumIter, EnumString};
use uuid::Uuid;

pub const EDGE_NAME: &str = "Proof_Forward";
pub const REVERSE_EDGE_NAME: &str = "Proof_Backward";
pub const IS_DIRECTED: bool = true;

#[derive(
    Serialize_repr,
    Deserialize_repr,
    Debug,
    Clone,
    Display,
    EnumString,
    PartialEq,
    Eq,
    EnumIter,
    Enum,
    Default,
    Copy,
)]
#[repr(i32)]
pub enum Level {
    /// "ignore_if_exists" or "~"
    #[default]
    /// Low confidence
    Insecure = 1,
    /// Moderate-low confidence
    Cautious = 2,
    /// Moderate confidence
    Neutral = 3,
    /// Moderate-high confidence
    Confident = 4,
    /// High confidence
    VeryConfident = 5,
}

/// Edge to connect two `Identity`s.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proof {
    /// UUID of this record. Generated by us to provide a better
    /// global-uniqueness for future P2P-network data exchange
    /// scenario.
    pub uuid: Uuid,
    /// Data source (upstream) which provides this connection info.
    pub source: DataSource,
    /// Level which provides this connection confidence level.
    pub level: Level,
    /// ID of this connection in upstream platform to locate (if any).
    pub record_id: Option<String>,
    /// When this connection is recorded in upstream platform (if platform gives such data).
    #[serde(deserialize_with = "option_naive_datetime_from_string")]
    #[serde(serialize_with = "option_naive_datetime_to_string")]
    pub created_at: Option<NaiveDateTime>,
    /// When this connection is fetched by us RelationService.
    #[serde(deserialize_with = "naive_datetime_from_string")]
    #[serde(serialize_with = "naive_datetime_to_string")]
    pub updated_at: NaiveDateTime,
    /// Who collects this data.
    /// It works as a "data cleansing" or "proxy" between `source`s and us.
    pub fetcher: DataFetcher,
}

impl Default for Proof {
    fn default() -> Self {
        Self {
            uuid: Uuid::new_v4(),
            source: DataSource::default(),
            level: Level::default(),
            record_id: None,
            created_at: None,
            updated_at: naive_now(),
            fetcher: Default::default(),
        }
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ProofRecord(pub EdgeRecord<Proof>);

impl FromWithParams<Proof> for EdgeRecord<Proof> {
    fn from_with_params(
        e_type: String,
        directed: bool,
        from_id: String,
        from_type: String,
        to_id: String,
        to_type: String,
        attributes: Proof,
    ) -> Self {
        EdgeRecord {
            e_type,
            directed,
            from_id,
            from_type,
            to_id,
            to_type,
            discriminator: None,
            attributes,
        }
    }
}

impl From<EdgeRecord<Proof>> for ProofRecord {
    fn from(record: EdgeRecord<Proof>) -> Self {
        ProofRecord(record)
    }
}

impl std::ops::Deref for ProofRecord {
    type Target = EdgeRecord<Proof>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl std::ops::DerefMut for ProofRecord {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ProofAttribute(HashMap<String, Attribute>);

// Implement the `From` trait for converting `ProofRecord` into a `HashMap<String, Attr>`.
impl Transfer for ProofRecord {
    fn to_attributes_map(&self) -> HashMap<String, Attribute> {
        let mut attributes_map = HashMap::new();
        attributes_map.insert(
            "uuid".to_string(),
            Attribute {
                value: json!(self.attributes.uuid.to_string()),
                op: Some(OpCode::IgnoreIfExists),
            },
        );
        attributes_map.insert(
            "source".to_string(),
            Attribute {
                value: json!(self.attributes.source.to_string()),
                op: None,
            },
        );
        attributes_map.insert(
            "level".to_string(),
            Attribute {
                value: to_value(&self.attributes.level).unwrap(),
                op: None,
            },
        );

        if let Some(record_id) = self.attributes.record_id.clone() {
            attributes_map.insert(
                "record_id".to_string(),
                Attribute {
                    value: json!(record_id),
                    op: None,
                },
            );
        }

        if let Some(created_at) = self.attributes.created_at {
            attributes_map.insert(
                "created_at".to_string(),
                Attribute {
                    value: json!(created_at),
                    op: Some(OpCode::IgnoreIfExists),
                },
            );
        }

        attributes_map.insert(
            "updated_at".to_string(),
            Attribute {
                value: json!(self.attributes.updated_at),
                op: Some(OpCode::Max),
            },
        );
        attributes_map.insert(
            "fetcher".to_string(),
            Attribute {
                value: json!(self.attributes.fetcher.to_string()),
                op: None,
            },
        );
        attributes_map
    }
}

impl Wrapper<ProofRecord, Identity, Identity> for Proof {
    fn wrapper(
        &self,
        from: &Identity,
        to: &Identity,
        name: &str,
    ) -> EdgeWrapper<ProofRecord, Identity, Identity> {
        let pb = EdgeRecord::from_with_params(
            name.to_string(),
            IS_DIRECTED,
            from.primary_key(),
            from.vertex_type(),
            to.primary_key(),
            to.vertex_type(),
            self.to_owned(),
        );
        EdgeWrapper {
            edge: ProofRecord(pb),
            source: from.to_owned(),
            target: to.to_owned(),
        }
    }
}

#[async_trait::async_trait]
impl Edge<Identity, Identity, ProofRecord> for ProofRecord {
    fn e_type(&self) -> String {
        self.e_type.clone()
    }

    fn directed(&self) -> bool {
        // TODO: query from server is the best solution
        self.directed.clone()
    }

    /// Connect 2 vertex.
    async fn connect(
        &self,
        client: &Client<HttpConnector>,
        from: &Identity,
        to: &Identity,
    ) -> Result<(), Error> {
        todo!()
    }
}

// #[derive(Debug, Clone, Deserialize, Serialize)]
// pub struct ProofWrapper(EdgeWrapper<ProofRecord, Identity, Identity>);

// impl ProofWrapper {
//     pub fn new(
//         proof: &impl Wrapper<ProofRecord, Identity, Identity>,
//         from: &Identity,
//         to: &Identity,
//         name: &str,
//     ) -> Self {
//         ProofWrapper(proof.wrapper(from, to, name))
//     }
// }
