name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: nextid-relation-service
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Building package
        run: nix build
