name: "Build Nix package on NixOS"

on:
  push:

jobs:
  nix-build:
    runs-on:
      labels: [nixos, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Building package
      run: nix build -v -L
    - name: Build docker
      run: nix bundle --bundler 'github:NixOS/bundlers#toDockerImage' .
